### ISSUE TITLE
[bug] latest yarn is broken

### ISSUE THREAD

**Issue by TFK70** [Atlantis-Lab/nextjs#178]
### Описание бага

Последний yarn работает некорректно на этой репе
   
### Воспроизведение
Шаги для воспроизведения бага:
1. Пытаемся установить зависимость в любой из воркспейсов, например:
`yarn workspace @atlantis-lab/next-app-with-emotion add @emotion/react`
2. Видим ошибку

### Ожидаемое поведение
Зависимость должна установиться

### Материалы

```javascript
error An unexpected error occurred: "expected workspace package to exist for \"yargs-parser\"".
info If you think this is a bug, please open a bug report with the information provided in "/media/darius/6E4CBE7A4CBE3D21/atlantis/atlantis/nextjs/packages/next-app-with-emotion/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
error Command failed.
Exit code: 1
```

### Примечания

`yarn install` работает без проблем

Как временный workaround - понизить версию yarn до 1.19

### Данные окружения
 - Ubuntu@20.04

**Comment by TorinAsakura** [comment]
Также как и в https://github.com/Atlantis-Lab/reactjs/issues/85 - проблема на Ubuntu
